// export const logo = "components/Multimedia/logo/Logo 1.png";

export const categorias = [
  { id: "0", name: "Ver todos" },
  { id: "1", name: "Mujeres" },
  { id: "2", name: "Hombres" },
  { id: "3", name: "Niños" },
];

export const productos = [
  {
    id: "1",
    catSexo: "1",
    catGral: "Prendas superiores",
    prenda: "Camisetas y henleys",
    subPrenda: ["Packde varias camisetas", "Manga corta", "Ver todos"],
    nombre: "Camisetas",
    descripcion: "Pack de 2 camisetas blanca y marron con escote bordado.",
    stock: 10,
    precio: 3000,
    imgCard: "../images/Ropa mujer/camiseta pack 2.webp",
    imgSub1: "",
    imgSub2: "",
    imgSub3: "",
    imgSub4: "",
    prodcutoLink: "",
  },
  {
    id: "2",
    catSexo: "1",
    catGral: "Prendas superiores",
    prenda: "Canguros",
    subPrenda: ["Ver todos", "Con capucha y cremallera"],
    nombre: "Campera rosa",
    descripcion: "Campera de algodon rosada con capucha.",
    stock: 6,
    precio: 2499,
    imgCard: "../images/Ropa mujer/Campera rosada2ff.jpg",
    imgSub1: "",
    imgSub2: "",
    imgSub3: "",
    imgSub4: "",
    prodcutoLink: "../pages/pag-capera-detalle.html",
  },
  {
    id: "3",
    catSexo: "1",
    catGral: "Prendas superiores",
    prenda: "Canguros",
    subPrenda: ["Ver todos", "Con capucha cerradas"],
    nombre: "Campera rosada",
    descripcion: "Campera de algodon rosada",
    stock: 2,
    precio: 3000,
    imgCard: "../images/Ropa mujer/Campera.webp",
    imgSub1: "",
    imgSub2: "",
    imgSub3: "",
    imgSub4: "",
    prodcutoLink: "",
  },
  {
    id: "4",
    catSexo: "1",
    catGral: "Prendas inferiores",
    prenda: "",
    subPrenda: ["Ver todos", "Shorts"],
    nombre: "Falda de cuero",
    descripcion: "Falda de cuero vegano estilo cuadriculado gama beig y blanca",
    stock: 3,
    precio: 1899,
    imgCard: "../images/Ropa mujer/falda.webp",
    imgSub1: "",
    imgSub2: "",
    imgSub3: "",
    imgSub4: "",
    prodcutoLink: "",
  },
  // {
  //   id: "5",
  //   catSexo: "1",
  //   catGral: "Prendas inferiores",
  //   prenda: "",
  //   subPrenda: ["Ver todos", "Jeans"],
  //   nombre: "Jeans",
  //   descripcion: "Jean de tido corto con terminacion acampanado tipo Oxford",
  //   stock: 12,
  //   precio: 1600,
  //   imgCard: "../images/Ropa mujer/Jeans.webp",
  //   imgSub1: "",
  //   imgSub2: "",
  //   imgSub3: "",
  //   imgSub4: "",
  //   prodcutoLink: "",
  // },
  // {
  //   id: "6",
  //   catSexo: "1",
  //   catGral: "Prendas superiores",
  //   prenda: "Canguros",
  //   subPrenda: ["Ver todos", "Cuello redondo"],
  //   nombre: "Campera",
  //   descripcion: "Campera de algodon cuello redondo",
  //   stock: 6,
  //   precio: 1899,
  //   imgCard: "../images/Ropa mujer/Sweter.webp",
  //   imgSub1: "",
  //   imgSub2: "",
  //   imgSub3: "",
  //   imgSub4: "",
  //   prodcutoLink: "",
  // },
  {
    id: "7",
    catSexo: "2",
    catGral: "Prendas superiores",
    prenda: "Canguros",
    subPrenda: ["Ver todos", "Con capucha y cremallera"],
    nombre: "Campera corderito",
    descripcion: "Campera deportiva corderito hollister, con capucha.",
    stock: 7,
    precio: 6500,
    imgCard: "../images/Ropa hombre/Campera.webp",
    imgSub1: "",
    imgSub2: "",
    imgSub3: "",
    imgSub4: "",
    prodcutoLink: "",
  },
  {
    id: "8",
    catSexo: "2",
    catGral: "Prendas superiores",
    prenda: "Canguros",
    subPrenda: [" Ver todos", "Con capucha cerradas"],
    nombre: "Campera Hollister",
    descripcion:
      "Campera deportiva Hollister con capucha estilo 2 colores en dregadado. ",
    stock: 3,
    precio: 3499,
    imgCard: "../images/Ropa hombre/2000001.1.webp",
    imgSub1: "",
    imgSub2: "",
    imgSub3: "",
    imgSub4: "",
    prodcutoLink: "../pages/pag-detalle-2000001.html",
  },
  // {
  //   id: "9",
  //   catSexo: "2",
  //   catGral: "Prendas superiores",
  //   prenda: "Camisetas y henleys",
  //   subPrenda: ["Ver todos", "Manga larga"],
  //   nombre: "Remera manga larga",
  //   descripcion:
  //     "Remera manga larga Hollister tiro redondo, estilo 2 colores en dregadado.",
  //   stock: 8,
  //   precio: 1499,
  //   imgCard: "../images/Ropa hombre/2000002.webp",
  //   imgSub1: "",
  //   imgSub2: "",
  //   imgSub3: "",
  //   imgSub4: "",
  //   prodcutoLink: "../pages/pag-detalle-2000002.html",
  // },
  // {
  //   id: "10",
  //   catSexo: "2",
  //   catGral: ["Prendas superiores", " Prendas inferiores"],
  //   prenda: "Suéteres",
  //   subPrenda: ["Ver todas", "Shorts", "Deportivos", "Cuello redondo"],
  //   nombre: "Campera y short deportivo",
  //   descripcion: "Kit de algodon deportivo, campera de cuello redondo y short",
  //   stock: 2,
  //   precio: 7299,
  //   imgCard: "../images/Ropa hombre/Kit campera pantalon deportivo.webp",
  //   imgSub1: "",
  //   imgSub2: "",
  //   imgSub3: "",
  //   imgSub4: "",
  //   prodcutoLink: "",
  // },
  // {
  //   id: "11",
  //   catSexo: "2",
  //   catGral: "Prendas inferiores",
  //   prenda: "",
  //   subPrenda: ["Ver todas", "Shorts"],
  //   nombre: "Short de baño",
  //   descripcion: "Short de baño tiro corto estilo dino surf",
  //   stock: 15,
  //   precio: 1899,
  //   imgCard: "../images/Ropa hombre/Short baño.webp",
  //   imgSub1: "",
  //   imgSub2: "",
  //   imgSub3: "",
  //   imgSub4: "",
  //   prodcutoLink: "",
  // },
  // {
  //   id: "12",
  //   catSexo: "2",
  //   catGral: "Prendas inferiores",
  //   prenda: "",
  //   subPrenda: ["Ver todas", "Shorts", "Jeans"],
  //   nombre: "Bermuda de jeans",
  //   descripcion: " Bermuda tipo gastada de jeans tiro corto.",
  //   stock: 8,
  //   precio: 2600,
  //   imgCard: "../images/Ropa hombre/Short hombre.webp",
  //   imgSub1: "",
  //   imgSub2: "",
  //   imgSub3: "",
  //   imgSub4: "",
  //   prodcutoLink: "",
  // },
  // {
  //   id: "13",
  //   catSexo: "3",
  //   catGral: "Prendas inferiores",
  //   prenda: "",
  //   subPrenda: ["Ver todas", "Jogging", "Jeans"],
  //   nombre: "Pantalon Jeans",
  //   descripcion: "Pantalon jeans elastico tiro largo ",
  //   stock: 16,
  //   precio: 2749,
  //   imgCard: "../images/Ropa ninos/3000001.webp",
  //   imgSub1: "",
  //   imgSub2: "",
  //   imgSub3: "",
  //   imgSub4: "",
  //   prodcutoLink: "../pages/pag-detalle-3000001.html",
  // },
  // {
  //   id: "14",
  //   catSexo: "3",
  //   catGral: "Prendas inferiores",
  //   prenda: "",
  //   subPrenda: ["Ver todas", "Shorts", "Jeans"],
  //   nombre: "Short de jeans",
  //   descripcion: "Short de jeans tiro corto",
  //   stock: 8,
  //   precio: 1499,
  //   imgCard: "../images/Ropa ninos/3000002.webp",
  //   imgSub1: "",
  //   imgSub2: "",
  //   imgSub3: "",
  //   imgSub4: "",
  //   prodcutoLink: "../pages/pag-detalle-3000002.html",
  // },
  {
    id: "15",
    catSexo: "3",
    catGral: "Prendas inferiores",
    prenda: "",
    subPrenda: ["Ver todas"],
    nombre: "Vestido",
    descripcion: "Vestido sin mangas con tirantes",
    stock: 3,
    precio: 499,
    imgCard: "../images/Ropa ninos/3000006.webp",
    imgSub1: "",
    imgSub2: "",
    imgSub3: "",
    imgSub4: "",
    prodcutoLink: "",
  },
  {
    id: "16",
    catSexo: "3",
    catGral: "Prendas superiores",
    prenda: "Camisetas y henleys",
    subPrenda: ["Ver todas", "Manga corta"],
    nombre: "Remera Mickey Mouse",
    descripcion: "Remera Mickey Mouse surf cuello redonde de niño/niña",
    stock: 10,
    precio: 299,
    imgCard: "../images/Ropa ninos/3000003.webp",
    imgSub1: "",
    imgSub2: "",
    imgSub3: "",
    imgSub4: "",
    prodcutoLink: "",
  },
  // {
  //   id: "17",
  //   catSexo: "3",
  //   catGral: "Prendas superiores",
  //   prenda: "Camisetas y henleys",
  //   subPrenda: ["Ver todas", "Manga corta"],
  //   nombre: "Remera estampada",
  //   descripcion: "Remera estampada de cuellos redondo tipo jering",
  //   stock: 42,
  //   precio: 399,
  //   imgCard: "../images/Ropa ninos/3000004.webp",
  //   imgSub1: "",
  //   imgSub2: "",
  //   imgSub3: "",
  //   imgSub4: "",
  //   prodcutoLink: "",
  // },
  // {
  //   id: "18",
  //   catSexo: "3",
  //   catGral: "Prendas superiores",
  //   prenda: "Camisetas y henleys",
  //   subPrenda: ["Ver todas", "Manga corta"],
  //   nombre: "Remera estampada",
  //   descripcion: "Remera estampada de cuellos redondo tipo jering",
  //   stock: 25,
  //   precio: 399,
  //   imgCard: "../images/Ropa ninos/3000005.webp",
  //   imgSub1: "",
  //   imgSub2: "",
  //   imgSub3: "",
  //   imgSub4: "",
  //   prodcutoLink: "",
  // },
];
